let err=new Error('发生错误')
// console.log(err)
throw err
console.log('222')